// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: Messages.proto
#ifndef GRPC_Messages_2eproto__INCLUDED
#define GRPC_Messages_2eproto__INCLUDED

#include "Messages.pb.h"

#include <functional>
#include <grpc/impl/codegen/port_platform.h>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace Messages {

class ContactTracer final {
 public:
  static constexpr char const* service_full_name() {
    return "Messages.ContactTracer";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::Messages::JudgeContactRequest, ::Messages::JudgeContactResponse>> JudgeContact(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::Messages::JudgeContactRequest, ::Messages::JudgeContactResponse>>(JudgeContactRaw(context));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::Messages::JudgeContactRequest, ::Messages::JudgeContactResponse>> AsyncJudgeContact(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::Messages::JudgeContactRequest, ::Messages::JudgeContactResponse>>(AsyncJudgeContactRaw(context, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::Messages::JudgeContactRequest, ::Messages::JudgeContactResponse>> PrepareAsyncJudgeContact(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::Messages::JudgeContactRequest, ::Messages::JudgeContactResponse>>(PrepareAsyncJudgeContactRaw(context, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void JudgeContact(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::Messages::JudgeContactRequest,::Messages::JudgeContactResponse>* reactor) = 0;
      #else
      virtual void JudgeContact(::grpc::ClientContext* context, ::grpc::experimental::ClientBidiReactor< ::Messages::JudgeContactRequest,::Messages::JudgeContactResponse>* reactor) = 0;
      #endif
    };
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    typedef class experimental_async_interface async_interface;
    #endif
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    async_interface* async() { return experimental_async(); }
    #endif
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientReaderWriterInterface< ::Messages::JudgeContactRequest, ::Messages::JudgeContactResponse>* JudgeContactRaw(::grpc::ClientContext* context) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::Messages::JudgeContactRequest, ::Messages::JudgeContactResponse>* AsyncJudgeContactRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::Messages::JudgeContactRequest, ::Messages::JudgeContactResponse>* PrepareAsyncJudgeContactRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    std::unique_ptr< ::grpc::ClientReaderWriter< ::Messages::JudgeContactRequest, ::Messages::JudgeContactResponse>> JudgeContact(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriter< ::Messages::JudgeContactRequest, ::Messages::JudgeContactResponse>>(JudgeContactRaw(context));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::Messages::JudgeContactRequest, ::Messages::JudgeContactResponse>> AsyncJudgeContact(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::Messages::JudgeContactRequest, ::Messages::JudgeContactResponse>>(AsyncJudgeContactRaw(context, cq, tag));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::Messages::JudgeContactRequest, ::Messages::JudgeContactResponse>> PrepareAsyncJudgeContact(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::Messages::JudgeContactRequest, ::Messages::JudgeContactResponse>>(PrepareAsyncJudgeContactRaw(context, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void JudgeContact(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::Messages::JudgeContactRequest,::Messages::JudgeContactResponse>* reactor) override;
      #else
      void JudgeContact(::grpc::ClientContext* context, ::grpc::experimental::ClientBidiReactor< ::Messages::JudgeContactRequest,::Messages::JudgeContactResponse>* reactor) override;
      #endif
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientReaderWriter< ::Messages::JudgeContactRequest, ::Messages::JudgeContactResponse>* JudgeContactRaw(::grpc::ClientContext* context) override;
    ::grpc::ClientAsyncReaderWriter< ::Messages::JudgeContactRequest, ::Messages::JudgeContactResponse>* AsyncJudgeContactRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReaderWriter< ::Messages::JudgeContactRequest, ::Messages::JudgeContactResponse>* PrepareAsyncJudgeContactRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_JudgeContact_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status JudgeContact(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::Messages::JudgeContactResponse, ::Messages::JudgeContactRequest>* stream);
  };
  template <class BaseClass>
  class WithAsyncMethod_JudgeContact : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_JudgeContact() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_JudgeContact() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status JudgeContact(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::Messages::JudgeContactResponse, ::Messages::JudgeContactRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestJudgeContact(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::Messages::JudgeContactResponse, ::Messages::JudgeContactRequest>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(0, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_JudgeContact<Service > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_JudgeContact : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_JudgeContact() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(0,
          new ::grpc_impl::internal::CallbackBidiHandler< ::Messages::JudgeContactRequest, ::Messages::JudgeContactResponse>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context) { return this->JudgeContact(context); }));
    }
    ~ExperimentalWithCallbackMethod_JudgeContact() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status JudgeContact(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::Messages::JudgeContactResponse, ::Messages::JudgeContactRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerBidiReactor< ::Messages::JudgeContactRequest, ::Messages::JudgeContactResponse>* JudgeContact(
      ::grpc::CallbackServerContext* /*context*/)
    #else
    virtual ::grpc::experimental::ServerBidiReactor< ::Messages::JudgeContactRequest, ::Messages::JudgeContactResponse>* JudgeContact(
      ::grpc::experimental::CallbackServerContext* /*context*/)
    #endif
      { return nullptr; }
  };
  #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
  typedef ExperimentalWithCallbackMethod_JudgeContact<Service > CallbackService;
  #endif

  typedef ExperimentalWithCallbackMethod_JudgeContact<Service > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_JudgeContact : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_JudgeContact() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_JudgeContact() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status JudgeContact(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::Messages::JudgeContactResponse, ::Messages::JudgeContactRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_JudgeContact : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_JudgeContact() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_JudgeContact() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status JudgeContact(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::Messages::JudgeContactResponse, ::Messages::JudgeContactRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestJudgeContact(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(0, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_JudgeContact : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_JudgeContact() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(0,
          new ::grpc_impl::internal::CallbackBidiHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context) { return this->JudgeContact(context); }));
    }
    ~ExperimentalWithRawCallbackMethod_JudgeContact() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status JudgeContact(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::Messages::JudgeContactResponse, ::Messages::JudgeContactRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerBidiReactor< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* JudgeContact(
      ::grpc::CallbackServerContext* /*context*/)
    #else
    virtual ::grpc::experimental::ServerBidiReactor< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* JudgeContact(
      ::grpc::experimental::CallbackServerContext* /*context*/)
    #endif
      { return nullptr; }
  };
  typedef Service StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef Service StreamedService;
};

}  // namespace Messages


#endif  // GRPC_Messages_2eproto__INCLUDED
