version: '3'

services:
  app:
    build: .
    devices:
      - /dev/isgx
    volumes:
      - ${RUST_SDK_ROOT}:/root/sgx
      - ${TEE_PSI}:/root/sgx/samplecode/tee-psi
      - ${TEE_PSI}/docker/script/init.sh:/root/sgx/init.sh
      - ../../grpc:/var/grpc
    tty: true
    env_file: ${TEE_PSI}/.env
    command: /root/sgx/init.sh
    working_dir: /root/sgx/samplecode/tee-psi